USE ROLE DEMO_ROLE;
INSERT INTO  PROJECT_COMMENTS (ID, COMMENTS) VALUES (10,'This is insert from my srcipt file');
INSERT INTO  PROJECT_TASK (TASK_ID,TASK_TYPE,TASK_DESC) VALUES (100,'Action','jimmy has update it ');
INSERT INTO  PROJECT_TASK (TASK_ID,TASK_TYPE,TASK_DESC) VALUES (101,'Suggestion','updated description we dont make a home page');
INSERT INTO PROJECT_COMMENTS (ID, COMMENTS) VALUES (11, 'WE UPDATED THE INSERTING STUFF');
UPDATE PROJECT_TASK SET TASK_DESC = 'ABDUL BASIT HAS UPDATE THIS RIGHT NOW' WHERE TASK_ID = 4;
DELETE FROM PROJECT_TASK WHERE TASK_ID = 2;