name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.9.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9.x

      - name: Run Snowflake-connector-python
        
        run:  |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing snowflake-connector-python"
          python3 -m pip install --upgrade pip
          pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v2.5.1/tested_requirements/requirements_38.reqs
          pip install snowflake-connector-python==2.5.1
 
          echo "Step 2: Running python file"
          python $GITHUB_WORKSPACE/dbscripts/snowflake_connector.py
          

